@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYWtlQHVzZXIuY29tIiwiZXhwIjoxNzgwNjU1ODA3fQ.y3NN96oanssQhC0AD0-L8aIkyL82hTaapuFhuJO-pic

GET http://localhost:8001/health

### Login with AuthKit
POST http://localhost:8000/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "email": "fake@user.com",
    "password": "verysecret"
}

### AuthKit me
GET http://localhost:8000/api/v1/auth/me HTTP/1.1
Authorization: Bearer {{token}}

###  Add a product
POST http://localhost:8001/api/v1/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "url": "https://www.amazon.it/dp/B0CHXMJRP3",
    "name": "Test Product",
    "alert_threshold": 99.99
}

### List products
GET http://localhost:8001/api/v1/products
Authorization: Bearer {{token}}

### Get a specific product
GET http://localhost:8001/api/v1/products/65fc385a-18c1-4019-aee5-99edce6d232b
Authorization: Bearer {{token}}

### Trigger a manual scrape
POST http://localhost:8001/api/v1/products/scrape HTTP/1.1
Authorization: Bearer {{token}}